### PR TITLE
Add Panel.ordered_panel_coordinates() method

### PR DESCRIPTION
**Pull request by and-viceversa**
Add method Panel.ordered_panel_coordinates() to return panel region coordinates in a predictable order to mirror ordering found by camera auto-detection.

### CODE REVIEW

**Comment by poynting** [comment]
Thanks for the PR.  Please rebase this on the latest master where I've fixed the ExifTool CI issue and see if that passes the CI.

**Comment by and-viceversa** [comment]
I may have done this rebase incorrectly. It looks like the Exiftool CI changes made it into the commit.

**Comment by poynting** [comment]
Thanks that seemed to work and still passes current tests. Can you do one more thing and add a couple of tests for this? 

Maybe something like this in `tests/test_panel.py`:

```
def test_ordered_coordinates(panel_image_name):
    img = image.Image(panel_image_name)
    ordered_corners = [[809, 613], [648, 615], [646, 454], [808, 452]]
    pan = panel.Panel(img, panelCorners=ordered_corners)
    assert panel.ordered_panel_coordinates == ordered_corners

def test_unordered_coordinates(panel_image_name):
    img = image.Image(panel_image_name)
    ordered_corners = [[809, 613], [648, 615], [646, 454], [808, 452]]
    unordered_corners = [[648, 615], [809, 613], [808, 452], [646, 454]]
    pan = panel.Panel(img, panelCorners=unordered_corners)
    assert panel.ordered_panel_coordinates == ordered_corners
```

(I just grabbed some code from the current panel tests and pasted it here, that may not work exactly as I expect it to)

**Comment by and-viceversa** [comment]
Added tests, the ones you recommended were right on. I can revert the unused import and whitespace changes if you'd like. They are just PyCharm's verision of [PEP8](https://www.python.org/dev/peps/pep-0008/) style.

**Comment by poynting** [comment]
Thanks 👍. Yes please remove the whitespace changes. I don't mind them but
they should be in a separate PR so that there isn't any confusion with
functionality changes.

**Comment by poynting** [comment]
Thanks, merged.

**Pull request merged**
